[build]
  base = "ui/"
  command = "bun install && bun run build && echo \"/api/* ${API_PROXY_URL}/api/:splat 200\" > dist/_redirects && echo \"/* /index.html 200\" >> dist/_redirects"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  API_PROXY_URL = "https://study-palette-api.onrender.com"

[context.deploy-preview.environment]
  API_PROXY_URL = "https://study-palette-dev.onrender.com"
