"""Load JSONL seed data into a per-study DuckDB file."""

import argparse
from pathlib import Path

import duckdb

TABLES = {
    "participant": "TOY-Participant--data.jsonl",
    "demography": "TOY-Demography--data.jsonl",
    "condition": "TOY-Condition--data.jsonl",
    "measurement_observation": "TOY-MeasurementObservation--data.jsonl",
    "observation": "TOY-Observation--data.jsonl",
}

STUDY_METADATA = {
    "id": "phs000000",
    "name": "Toy Study: Synthetic dbGaP Dataset",
    "description": "A synthetic dataset generated by dm-bip for pipeline testing. "
    "Contains 110 participants with demographics, conditions, measurements, and observations.",
}


def load(seed_dir: Path, data_dir: Path) -> Path:
    """Read JSONL files from seed_dir and write a .duckdb file to data_dir."""
    data_dir.mkdir(parents=True, exist_ok=True)
    db_path = data_dir / f"{STUDY_METADATA['id']}.duckdb"

    con = duckdb.connect(str(db_path))
    try:
        con.execute(
            "CREATE TABLE IF NOT EXISTS research_study ("
            "id VARCHAR PRIMARY KEY, name VARCHAR, description VARCHAR)"
        )
        con.execute(
            "INSERT OR REPLACE INTO research_study VALUES (?, ?, ?)",
            [STUDY_METADATA["id"], STUDY_METADATA["name"], STUDY_METADATA["description"]],
        )

        for table_name, filename in TABLES.items():
            jsonl_path = seed_dir / filename
            if not jsonl_path.exists():
                print(f"  skipping {filename} (not found)")
                continue
            con.execute(f"DROP TABLE IF EXISTS {table_name}")  # noqa: S608
            safe_path = jsonl_path.as_posix().replace("'", "''")
            con.execute(
                f"CREATE TABLE {table_name} AS "  # noqa: S608
                f"SELECT * FROM read_json_auto('{safe_path}')"
            )
            count = con.execute(f"SELECT count(*) FROM {table_name}").fetchone()[0]  # noqa: S608
            print(f"  {table_name}: {count} rows")
    finally:
        con.close()

    print(f"Wrote {db_path}")
    return db_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Load seed data into DuckDB")
    parser.add_argument("--seed-dir", type=Path, default=Path("api/seed_data"))
    parser.add_argument("--data-dir", type=Path, default=Path("data"))
    args = parser.parse_args()
    load(args.seed_dir, args.data_dir)
